version: "3"

services:

  govbuy-theme:
    build: .
    image: orihoch/open-procure
    volumes:
    - ./govbuy-theme:/app/dist/assets

  item:
    image: budgetkey/budgetkey-app-generic-item:latest
    depends_on:
    - govbuy-theme
    environment:
    - BASE_PATH=/item/
    volumes:
    - ./govbuy-theme/theme.js:/app/dist/assets/theme.js

  search:
    image: orihoch/budgetkey-app-search:themes-support
    depends_on:
    - govbuy-theme
    volumes:
    - ./govbuy-theme/theme.js:/app/dist/assets/theme.js

  nginx:
    image: nginx:alpine
    ports:
    - 8080:80
    volumes:
    - ./nginx-conf-d:/etc/nginx/conf.d
